### ISSUE TITLE
Standalone site set-up problem

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#56]
I'm trying to run HistoneDB on my local Mac.
after downloading the project and setting up MySQL database,
a do "python manage.py migrate", and get an error - see below.

Running "python manage.py migrate" the next time does not throw an error, but this is kind of strange.

(env)MBRetina:HistoneDB alex$ python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: staticfiles, browse, django_extensions, messages
  Apply all migrations: admin, contenttypes, sessions, auth, djangophylocore
Synchronizing apps without migrations:
  Creating tables...
    Creating table browse_histone
    Creating table browse_variant
    Creating table browse_oldstylevariant
    Creating table browse_sequence
    Creating table browse_score
    Creating table browse_features
    Creating table browse_structure
    Creating table browse_publication
    Running deferred SQL...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/alexeyshaytan/histdb_data/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/alexeyshaytan/histdb_data/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/alexeyshaytan/histdb_data/env/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/alexeyshaytan/histdb_data/env/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/Users/alexeyshaytan/histdb_data/env/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 179, in handle
    created_models = self.sync_apps(connection, executor.loader.unmigrated_apps)
  File "/Users/alexeyshaytan/histdb_data/env/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 317, in sync_apps
    cursor.execute(statement)
  File "/Users/alexeyshaytan/histdb_data/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/alexeyshaytan/histdb_data/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/alexeyshaytan/histdb_data/env/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/alexeyshaytan/histdb_data/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/Users/alexeyshaytan/histdb_data/env/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/Users/alexeyshaytan/histdb_data/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/Users/alexeyshaytan/histdb_data/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.IntegrityError: (1215, 'Cannot add foreign key constraint')

**Comment by edraizen** [comment]
This was fixed by adding "SET FOREIGN_KEY_CHECK=0;" to mysql calls in djangophylcore/browse/management/commands/loadtaxonomy.py
